### ISSUE TITLE
Needs to Re-Run the Server or Update it

### ISSUE THREAD

**Issue by eneskemalergin** [NAU-ACM/ACM-Showcase#6]
In order to show the changes on the actual website please learn how to update the server and re-run it from @mburakergenc, I believe he has access.

@BedirT @MichaelMMeskhi @AhmetHamzaEmra

**Comment by MichaelMMeskhi** [comment]
The website is working and its at acm.na.edu<http://acm.na.edu>

Michael M.Meskhi<http://michaelmm.com>
------------------------
Software Engineering Student @NAU
Pattern Analysis Lab Member @UH
Phone: +1 (346) 317 2386
m.meskhi@na.edu<mailto:m.meskhi@na.edu>
Stack Overflow<http://stackoverflow.com/users/5110035/>
Github<https://github.com/michaelmmeskhi>



On Oct 25, 2017, at 11:39 AM, Enes Kemal Ergin <notifications@github.com<mailto:notifications@github.com>> wrote:


In order to show the changes on the actual website please learn how to update the server and re-run it from @mburakergenc<https://github.com/mburakergenc>, I believe he has access.

@BedirT<https://github.com/bedirt> @MichaelMMeskhi<https://github.com/michaelmmeskhi> @AhmetHamzaEmra<https://github.com/ahmethamzaemra>

**Comment by mburakergenc** [comment]
Do you host it yourself at school or on somewhere else? @MichaelMMeskhi.

**Comment by MichaelMMeskhi** [comment]
It’s on Github with a CNAME directing to A record for acm.na.edu<http://acm.na.edu>

Michael M.Meskhi<http://michaelmm.com>
------------------------
Software Engineering Student @NAU
Pattern Analysis Lab Member @UH
Phone: +1 (346) 317 2386
m.meskhi@na.edu<mailto:m.meskhi@na.edu>
Stack Overflow<http://stackoverflow.com/users/5110035/>
Github<https://github.com/michaelmmeskhi>



On Oct 25, 2017, at 12:28 PM, Muhammet Burak Ergenc <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you host it yourself at school or on somewhere else? @MichaelMMeskhi<https://github.com/michaelmmeskhi>.

**Comment by eneskemalergin** [comment]
Very Cool

**Comment by eneskemalergin** [comment]
It's good to see development, keep it up you guys, @MichaelMMeskhi . More blogposts needed though.

**Comment by MichaelMMeskhi** [comment]
Am trying. Just a bit busy with research. Thank for helping out!

Michael M.Meskhi<http://michaelmm.com>
------------------------
Software Engineering Student @NAU
Pattern Analysis Lab Member @UH
Phone: +1 (346) 317 2386
m.meskhi@na.edu<mailto:m.meskhi@na.edu>
Stack Overflow<http://stackoverflow.com/users/5110035/>
Github<https://github.com/michaelmmeskhi>



On Oct 25, 2017, at 12:39 PM, Enes Kemal Ergin <notifications@github.com<mailto:notifications@github.com>> wrote:


It's good to see development, keep it up you guys, @MichaelMMeskhi<https://github.com/michaelmmeskhi> . More blogposts needed though.
